version: '2.1'

services:
  elasticsearch:
    image: elasticsearch:${ELK_VERSION}
    environment:
      - ES_JAVA_OPTS:-Xmx256m -Xms256m
    volumes:
      - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      elk:      
        
  logstash:
    image: logstash:${ELK_VERSION}
    environment:
      - LS_JAVA_OPTS:-Xmx256m -Xms256m
    ports:
      - 5514:5514
      - 5515:5515
      - 5516:5516
      - 5517:5517
    volumes:
      - ./conf/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./conf//logstash_main.conf:/usr/share/logstash/pipeline/logstash_main.conf
      - ./conf/pem:/opt/elk/pem
    networks:
      elk:      
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:${ELK_VERSION}
    volumes:
      - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elkdata:
